version: '2'
checks:
  method-lines:
    config:
      threshold: 35
plugins:
  eslint:
    enabled: true
    channel: 'eslint-5'
    config:
      ignore_warnings: true
      config: .eslintrc
  stylelint:
    enabled: true
    config:
      ignore_warnings: true
      config: .stylelintrc
  editorconfig:
    enabled: true
    channel: beta
    config:
      editorconfig: .editorconfig
exclude_patterns:
  - node_modules/
  - .next/
  - static/
  - public/
  - .vscode/
